export const DECLINE_DETAIL_DATA = [
  {
    id: 14414352,
    transactionId: '240227008547390294',
    operationTime: '2024-02-27T10:21:14',
    expiredDate: '2027-09-30T00:00:00',
    pseudoPan: '409809TYDELM8036',
    amount: null,
    currency: 944,
    merchantName: 'Unibank',
    prodType: '14VCUCARD',
    result: 'PIN_AUTH_FAILED',
    resultText: 'PinAuthFailed',
    declineReason: null,
    acquirerId: 31,
    dpan: null,
    dpanWalletRid: null,
    tds: 'UNKNOWN',
    fullName: 'ABBASOV VİDADİ NADİR OĞLU',
    mobilePhone: 502225256,
    finCode: '0Y437J4',
    cardStatus: null,
    aznEquivalent: null,
    creditLimit: null,
    entryMode: null,
    availableBalance: null,
  },
  {
    id: 14414353,
    transactionId: '240227008547391038',
    operationTime: '2024-02-27T10:21:19',
    expiredDate: '2027-06-30T00:00:00',
    pseudoPan: '524375WPZHTA8894',
    amount: 1560.0,
    currency: 944,
    merchantName: 'Unibank',
    prodType: 'MAADWC',
    result: 'UNKNOWN',
    resultText: 'InsufficientFunds',
    declineReason:
      "Standard available balance: -382.04, local credit holds: 380, credit limit: 0, total -2.04\nAccount #08217446941010AZN001 (owner: `Contract: 1647058) 'YAQUBOV HAMID NARIMANOGLU' - Shadow Account Contract')\n\ncontract `1647058) 'YAQUBOV HAMID NARIMANOGLU' - Shadow Account Contract' available balance after this transaction would be -2.04 AZN.,\nentry components:\n  Entry type: 'Main entry', Sign: Debit, Register role: 'Current account', Account: 08217446941010AZN001, Amount: 1560.00, Currency: AZN, Amount in institution currency: 1560.00, Amount in account currency: 1560.00;\n  Entry type: 'Main entry', Sign: Credit, Account: 001FI9440000015302, Amount: 1560.00, Currency: AZN, Amount in institution currency: 1560.00, Amount in account currency: 1560.00;\n  Entry type: 'Transaction fee', Tariff version: 669) P2P AFT Unibank to Domestic - v.3392, Sign: Debit, Register role: 'Current account', Account: 08217446941010AZN001, Amount: 2.0400000000, Currency: AZN, Amount in institution currency: 2.04, Amount in account currency: 2.04;\n  Entry type: 'Transaction fee', Tariff version: 669) P2P AFT Unibank to Domestic - v.3392, Sign: Credit, Account: 001FI9440000001729, Amount: 2.0400000000, Currency: AZN, Amount in institution currency: 2.04, Amount in account currency: 2.0400000000;",
    acquirerId: 31,
    dpan: null,
    dpanWalletRid: null,
    tds: 'UNKNOWN',
    fullName: 'YAQUBOV HƏMİD NƏRİMAN OĞLU',
    mobilePhone: 552523988,
    finCode: '246BKW0',
    cardStatus: 'Active',
    aznEquivalent: 1560,
    creditLimit: null,
    entryMode: 'CredentialOnFile',
    availableBalance: 1560,
  },
  {
    id: 14414383,
    transactionId: '240227008547415248',
    operationTime: '2024-02-27T10:24:12',
    expiredDate: '2029-12-31T00:00:00',
    pseudoPan: '524375YBAGLW5765',
    amount: null,
    currency: 944,
    merchantName: 'Unibank',
    prodType: 'MCAUCARD',
    result: 'PIN_AUTH_FAILED',
    resultText: 'PinAuthFailed',
    declineReason: null,
    acquirerId: 31,
    dpan: null,
    dpanWalletRid: null,
    tds: 'UNKNOWN',
    fullName: 'MEHDİYEVA GÜLNAZ HİDAYƏT QIZI',
    mobilePhone: 554218809,
    finCode: '4YTLH1N',
    cardStatus: null,
    aznEquivalent: null,
    creditLimit: null,
    entryMode: null,
    availableBalance: null,
  },

  {
    id: 14414392,
    transactionId: '240227008547421049',
    operationTime: '2024-02-27T10:24:48',
    expiredDate: '2027-09-30T00:00:00',
    pseudoPan: '409809TYDELM8036',
    amount: null,
    currency: 944,
    merchantName: 'Unibank',
    prodType: '14VCUCARD',
    result: 'PIN_TRY_EXCEEDED',
    resultText: 'PinTryExceeded',
    declineReason: null,
    acquirerId: 31,
    dpan: null,
    dpanWalletRid: null,
    tds: 'UNKNOWN',
    fullName: 'ABBASOV VİDADİ NADİR OĞLU',
    mobilePhone: 502225256,
    finCode: '0Y437J4',
    cardStatus: null,
    aznEquivalent: null,
    creditLimit: null,
    entryMode: null,
    availableBalance: null,
  },
  {
    id: 14414377,
    transactionId: '240227008547409161',
    operationTime: '2024-02-27T10:23:30',
    expiredDate: '2027-03-31T00:00:00',
    pseudoPan: '409809LQDMCZ2877',
    amount: null,
    currency: 944,
    merchantName: 'Unibank',
    prodType: '14VCUCARD',
    result: 'PIN_AUTH_FAILED',
    resultText: 'PinAuthFailed',
    declineReason: 'Authentication failed',
    acquirerId: 31,
    dpan: null,
    dpanWalletRid: null,
    tds: 'UNKNOWN',
    fullName: 'İSMAYILOVA ZÜMRÜD SALEH QIZI',
    mobilePhone: 502184101,
    finCode: '27U5G50',
    cardStatus: 'Active',
    aznEquivalent: 0,
    creditLimit: null,
    entryMode: 'IccContactless',
    availableBalance: 216.17,
  },
  {
    id: 14414378,
    transactionId: '240227008547409924',
    operationTime: '2024-02-27T10:23:36',
    expiredDate: '2029-12-31T00:00:00',
    pseudoPan: '524375DQAZPJ5732',
    amount: null,
    currency: 944,
    merchantName: 'Unibank',
    prodType: 'MCAUCARD',
    result: 'PIN_AUTH_FAILED',
    resultText: 'PinAuthFailed',
    declineReason: 'Authentication failed',
    acquirerId: 31,
    dpan: null,
    dpanWalletRid: null,
    tds: 'UNKNOWN',
    fullName: 'HƏSƏNOV CEYHUN HİLAL OĞLU',
    mobilePhone: 552228510,
    finCode: '5XWX8W3',
    cardStatus: 'Active',
    aznEquivalent: 0,
    creditLimit: null,
    entryMode: 'IccContactless',
    availableBalance: 350.24,
  },
  {
    pageable: {
      sort: {
        empty: true,
        sorted: false,
        unsorted: true,
      },
      offset: 0,
      pageSize: 10,
      pageNumber: 0,
      paged: true,
      unpaged: false,
    },
    totalElements: 6,
    totalPages: 1,
    last: true,
    sort: {
      empty: true,
      sorted: false,
      unsorted: true,
    },
    size: 10,
    number: 0,
    numberOfElements: 6,
    first: true,
    empty: false,
  },
];

export const DECLINE_LIST_DATA = [
  {
    number: 1,
    type: 'Unibank',
    count: 8,
  },
  {
    number: 2,
    type: 'APPLE.COM/BILL',
    count: 8,
  },
  {
    number: 3,
    type: 'Azercell',
    count: 3,
  },
  {
    number: 4,
    type: 'ATM ELMLAR METRO',
    count: 2,
  },
  {
    number: 5,
    type: 'TIKINTI MAT.MAG',
    count: 2,
  },
  {
    number: 6,
    type: 'GOOGLE *Royal Match',
    count: 2,
  },
  {
    number: 7,
    type: 'Google Getcontact',
    count: 2,
  },
  {
    number: 8,
    type: 'KAPS',
    count: 2,
  },
  {
    number: 9,
    type: 'ATM UNIPLAZA',
    count: 1,
  },
  {
    number: 10,
    type: 'ATM ICHERI SHEHER BRANCH',
    count: 1,
  },
];

export const COLUMNS = [
  {
    key: 'id',
    label: 'Id',
    display: false,
    checked: false,
  },
  {
    key: 'transactionId',
    label: 'Transaction Id',
    display: true,
    checked: false,
  },
  {
    key: 'operationTime',
    label: 'Operation Time',
    display: false,
    checked: false,
  },
  {
    key: 'expiredDate',
    label: 'Expired Date',
    display: false,
    checked: false,
  },
  {
    key: 'pseudoPan',
    label: 'Pseudo Pan',
    display: false,
    checked: false,
  },
  {
    key: 'amount',
    label: 'Amount',
    display: true,
    checked: false,
  },
  {
    key: 'currency',
    label: 'Currency',
    display: false,
    checked: false,
  },
  {
    key: 'merchantName',
    label: 'Merchant Name',
    display: false,
    checked: false,
  },
  {
    key: 'prodType',
    label: 'Prod Type',
    display: false,
    checked: false,
  },
  {
    key: 'result',
    label: 'Result',
    display: false,
    checked: false,
  },
  {
    key: 'resultText',
    label: 'Result Text',
    display: false,
    checked: false,
  },
  {
    key: 'declineReason',
    label: 'Decline Reason',
    display: false,
    checked: false,
  },
  {
    key: 'acquirerId',
    label: 'Acquirer Id',
    display: false,
    checked: false,
  },
  {
    key: 'dpan',
    label: 'Dpan',
    display: false,
    checked: false,
  },
  {
    key: 'dpanWalletRid',
    label: 'Dpan Wallet Rid',
    display: false,
    checked: false,
  },
  {
    key: 'tds',
    label: 'Tds',
    display: false,
    checked: false,
  },
  {
    key: 'fullName',
    label: 'Full Name',
    display: true,
    checked: false,
  },
  {
    key: 'mobilePhone',
    label: 'Mobile Phone',
    display: false,
    checked: false,
  },
  {
    key: 'finCode',
    label: 'Fin Code',
    display: false,
  },
  {
    key: 'cardStatus',
    label: 'Card Status',
    display: false,
    checked: false,
  },
  {
    key: 'aznEquivalent',
    label: 'Azn Equivalent',
    display: false,
    checked: false,
  },
  {
    key: 'creditLimit',
    label: 'Credit Limit',
    display: false,
    checked: false,
  },
  {
    key: 'entryMode',
    label: 'Entry Mode',
    display: false,
    checked: false,
  },
  {
    key: 'availableBalance',
    label: 'Available Balance',
    display: false,
    checked: false,
  },
];

export const DECLINE_COLUMNS = [
  {
    key: 'number',
    label: 'Number',
    display: true,
  },
  {
    key: 'type',
    label: 'Type',
    display: true,
  },
  {
    key: 'count',
    label: 'Count',
    display: true,
  },
];

export const FILTERS = [
  {
    value: '0',
    label: 'Merchant Name',
    checked: false,
    display: false,
  },
  {
    value: '1',
    label: 'PAN',
    checked: false,
    display: false,
  },
  {
    value: '2',
    label: 'Decline result',
    checked: false,
    display: false,
  },
];
